name: coronaminder
description: Coronavirus tips
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  expandable: ^4.1.2
  splashscreen:


dev_dependencies:
  http: '0.11.3+17'
  webfeed: ^0.4.2
  cached_network_image: 2.0.0-rc
  url_launcher: any
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/
    - videos/
    - files/